version: '3'
services:
  # Service for Server A
  server_a:
    image: nginx:alpine
    container_name: server_a
    volumes:
      - ./server_a:/usr/share/nginx/html
    networks:
      - webnet

  # Service for Server B
  server_b:
    image: nginx:alpine
    container_name: server_b
    volumes:
      - ./server_b:/usr/share/nginx/html
    networks:
      - webnet

  # Service for Server C
  server_c:
    image: nginx:alpine
    container_name: server_c
    volumes:
      - ./server_c:/usr/share/nginx/html
    networks:
      - webnet

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: nginx_reverse_proxy
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server_a
      - server_b
      - server_c
    networks:
      - webnet

networks:
  webnet:
